### ISSUE TITLE
Does not work with Ruby 3.2 - uses deprecated File.exists? method

### ISSUE THREAD

**Issue by lauer** [leandrosardi/csv-indexer#2]
undefined method `exists?' for File:Class (NoMethodError) Did you mean? exist?

https://bugs.ruby-lang.org/issues/17391

Hotfixed in my quick test with 
```ruby
  class File
    def self.exists?(file)
      self.exist?(file)
    end
  end
```

**Comment by leandrosardi** [comment]
Thank you for collaborating with this project @lauer.

Feel free to fork this repository and submit a pull-request with your patches.
